spring:
  datasource:
    url: jdbc:h2:mem:maindb
  h2:
    console:
      enabled: true
  liquibase:
    enabled: true
    drop-first: false
    change-log: classpath:db/changelog/db.changelog-master.yaml
    contexts: main

